<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataLombaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('data_lomba')->insert([
            [
                'nama_lomba' => 'Kompetisi Pemrograman Nasional',
                'tgl_dibuka' => '2025-01-10',
                'tgl_ditutup' => '2025-12-20',
                'tingkat' => 3,
                'jenis' => 1,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Institut Teknologi Bandung',
                'alamat' => 'Jl. Ganesha No. 10, Bandung',
                'link_lomba' => 'https://kompetisi-itb.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 12.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Cyber Defense Competition',
                'tgl_dibuka' => '2025-08-05',
                'tgl_ditutup' => '2025-09-10',
                'tingkat' => 3,
                'jenis' => 2,
                'tingkat_penyelenggara' => 'Organisasi',
                'penyelenggara' => 'ID-CERT',
                'alamat' => 'Jakarta Selatan',
                'link_lomba' => 'https://cyberdefense.id',
                'biaya' => 50000,
                'hadiah' => 'Rp 6.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Challenge Pengembangan Perangkat Lunak',
                'tgl_dibuka' => '2025-03-05',
                'tgl_ditutup' => '2025-04-10',
                'tingkat' => 2,
                'jenis' => 3,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Komunitas Dev Surabaya',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://devsurabaya.org/challenge',
                'biaya' => 25000,
                'hadiah' => 'Rp 7.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Indonesia Coding Sprint',
                'tgl_dibuka' => '2025-05-03',
                'tgl_ditutup' => '2025-05-18',
                'tingkat' => 2,
                'jenis' => 4,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'PT Digital Nusantara',
                'alamat' => 'Online',
                'link_lomba' => 'https://codingsprint.id',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Kompetisi Data Sains',
                'tgl_dibuka' => '2025-06-15',
                'tgl_ditutup' => '2025-07-15',
                'tingkat' => 3,
                'jenis' => 5,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Universitas Sebelas Maret',
                'alamat' => 'Solo',
                'link_lomba' => 'https://datasains.uns.ac.id',
                'biaya' => 100000,
                'hadiah' => 'Rp 9.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'AI National Competition',
                'tgl_dibuka' => '2025-07-05',
                'tgl_ditutup' => '2025-08-05',
                'tingkat' => 2,
                'jenis' => 6,
                'tingkat_penyelenggara' => 'Organisasi',
                'penyelenggara' => 'AI Center Indonesia',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://aicenter.id/competition',
                'biaya' => 0,
                'hadiah' => 'Rp 8.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Kompetisi Desain Antarmuka',
                'tgl_dibuka' => '2025-09-05',
                'tgl_ditutup' => '2025-09-25',
                'tingkat' => 2,
                'jenis' => 7,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Universitas Ciputra',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://desain.ciputra.ac.id',
                'biaya' => 30000,
                'hadiah' => 'Rp 4.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Game Creation Contest',
                'tgl_dibuka' => '2025-10-05',
                'tgl_ditutup' => '2025-11-05',
                'tingkat' => 2,
                'jenis' => 8,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'GameDev Indonesia',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://gamedev.id/contest',
                'biaya' => 0,
                'hadiah' => 'Rp 5.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Network Engineering Competition',
                'tgl_dibuka' => '2025-11-05',
                'tgl_ditutup' => '2025-12-05',
                'tingkat' => 2,
                'jenis' => 9,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'PT Netindo',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://netindo.id/competition',
                'biaya' => 40000,
                'hadiah' => 'Rp 2.500.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Kompetisi Robotika Nasional',
                'tgl_dibuka' => '2025-06-05',
                'tgl_ditutup' => '2025-07-05',
                'tingkat' => 3,
                'jenis' => 10,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Universitas Negeri Makassar',
                'alamat' => 'Makassar',
                'link_lomba' => 'https://robotika.unm.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'IoT National Challenge',
                'tgl_dibuka' => '2025-03-20',
                'tgl_ditutup' => '2025-04-20',
                'tingkat' => 2,
                'jenis' => 11,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'IoT Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://iotindonesia.id/challenge',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'IoT Challenge Undip',
                'tgl_dibuka' => '2025-03-15',
                'tgl_ditutup' => '2025-04-15',
                'tingkat' => 2,
                'jenis' => 11,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Diponegoro',
                'alamat' => 'Semarang',
                'link_lomba' => 'https://iotchallenge.undip.ac.id',
                'biaya' => 20000,
                'hadiah' => 'Rp 2.500.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nama_lomba' => 'Business Case Competition',
                'tgl_dibuka' => '2025-04-01',
                'tgl_ditutup' => '2025-05-01',
                'tingkat' => 2,
                'jenis' => 12,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Airlangga',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://businesscase.unair.ac.id',
                'biaya' => 15000,
                'hadiah' => 'Rp 3.500.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Mobile Development Competition',
                'tgl_dibuka' => '2025-05-10',
                'tgl_ditutup' => '2025-06-10',
                'tingkat' => 2,
                'jenis' => 13,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Padjadjaran',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://mobiledev.unpad.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 4.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Web Development Challenge',
                'tgl_dibuka' => '2025-07-15',
                'tgl_ditutup' => '2025-08-15',
                'tingkat' => 2,
                'jenis' => 14,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Negeri Jakarta',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://webdev.unj.ac.id',
                'biaya' => 25000,
                'hadiah' => 'Rp 3.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Digital Animation Contest',
                'tgl_dibuka' => '2025-08-10',
                'tgl_ditutup' => '2025-09-10',
                'tingkat' => 2,
                'jenis' => 15,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Institut Seni Indonesia',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://animation.isi.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Cloud Computing Competition',
                'tgl_dibuka' => '2025-09-15',
                'tgl_ditutup' => '2025-10-15',
                'tingkat' => 2,
                'jenis' => 16,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Kristen Petra',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://cloudcomp.ukp.ac.id',
                'biaya' => 50000,
                'hadiah' => 'Rp 2.500.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Digital Forensics Challenge',
                'tgl_dibuka' => '2025-10-20',
                'tgl_ditutup' => '2025-11-20',
                'tingkat' => 2,
                'jenis' => 17,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Trunojoyo Madura',
                'alamat' => 'Bangkalan',
                'link_lomba' => 'https://forensics.trunojoyo.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Cryptography Challenge',
                'tgl_dibuka' => '2025-11-25',
                'tgl_ditutup' => '2025-12-25',
                'tingkat' => 2,
                'jenis' => 18,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Sanata Dharma',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://crypto.usd.ac.id',
                'biaya' => 10000,
                'hadiah' => 'Rp 1.500.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Lomba Desain UI/UX',
                'tgl_dibuka' => '2025-02-01',
                'tgl_ditutup' => '2025-03-01',
                'tingkat' => 2,
                'jenis' => 19,
                'tingkat_penyelenggara' => 'Kampus Lain ',
                'penyelenggara' => 'Politeknik Negeri Malang',
                'alamat' => 'Jl. Soekarno Hatta No. 10, Malang',
                'link_lomba' => 'https://uiux-poltek.com',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Hackathon Inovasi Digital',
                'tgl_dibuka' => '2025-04-10',
                'tgl_ditutup' => '2025-05-10',
                'tingkat' => 2,
                'jenis' => 20,
                'tingkat_penyelenggara' => 'Kampus Lain ',
                'penyelenggara' => 'Dinas Kominfo Jawa Timur',
                'alamat' => 'Jl. A. Yani No. 20, Surabaya',
                'link_lomba' => 'https://hackathon-jatim.go.id',
                'biaya' => 75000,
                'hadiah' => 'Rp 7.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Startup Pitch Competition',
                'tgl_dibuka' => '2025-01-15',
                'tgl_ditutup' => '2025-02-15',
                'tingkat' => 2,
                'jenis' => 21,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Prasetiya Mulya',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://startup.prasmul.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 5.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Algorithm Design Competition',
                'tgl_dibuka' => '2025-03-20',
                'tgl_ditutup' => '2025-04-20',
                'tingkat' => 2,
                'jenis' => 22,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Atma Jaya',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://algodesign.uajy.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Machine Learning Competition',
                'tgl_dibuka' => '2025-05-20',
                'tgl_ditutup' => '2025-06-20',
                'tingkat' => 2,
                'jenis' => 23,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Hasanuddin',
                'alamat' => 'Makassar',
                'link_lomba' => 'https://ml.hasanuddin.ac.id',
                'biaya' => 30000,
                'hadiah' => 'Rp 4.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Augmented Reality Competition',
                'tgl_dibuka' => '2025-07-20',
                'tgl_ditutup' => '2025-08-20',
                'tingkat' => 2,
                'jenis' => 24,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Negeri Semarang',
                'alamat' => 'Semarang',
                'link_lomba' => 'https://ar.unnes.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Virtual Reality Competition',
                'tgl_dibuka' => '2025-09-20',
                'tgl_ditutup' => '2025-10-20',
                'tingkat' => 2,
                'jenis' => 25,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Negeri Yogyakarta',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://vr.uny.ac.id',
                'biaya' => 20000,
                'hadiah' => 'Rp 2.500.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Blockchain Challenge Indonesia',
                'tgl_dibuka' => '2025-11-20',
                'tgl_ditutup' => '2025-12-20',
                'tingkat' => 2,
                'jenis' => 26,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Gunadarma',
                'alamat' => 'Depok',
                'link_lomba' => 'https://blockchain.gunadarma.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 3.500.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'App Innovation Competition',
                'tgl_dibuka' => '2025-01-05',
                'tgl_ditutup' => '2025-02-05',
                'tingkat' => 2,
                'jenis' => 27,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Katolik Parahyangan',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://appinnovation.unpar.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Database Design Competition',
                'tgl_dibuka' => '2025-03-05',
                'tgl_ditutup' => '2025-04-05',
                'tingkat' => 2,
                'jenis' => 28,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Kristen Satya Wacana',
                'alamat' => 'Salatiga',
                'link_lomba' => 'https://dbdesign.uksw.edu',
                'biaya' => 10000,
                'hadiah' => 'Rp 2.500.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Digital Marketing Competition',
                'tgl_dibuka' => '2025-05-05',
                'tgl_ditutup' => '2025-06-05',
                'tingkat' => 2,
                'jenis' => 29,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Mercu Buana',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://digitalmarketing.mercubuana.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'E-Sports Tournament',
                'tgl_dibuka' => '2025-07-05',
                'tgl_ditutup' => '2025-08-05',
                'tingkat' => 2,
                'jenis' => 30,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Negeri Malang',
                'alamat' => 'Malang',
                'link_lomba' => 'https://esports.um.ac.id',
                'biaya' => 50000,
                'hadiah' => 'Rp 5.000.000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
