<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataLombaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('data_lomba')->insert([
            // Jenis 1: Pemrograman Kompetitif
            [
                'nama_lomba' => 'Kompetisi Pemrograman Nasional',
                'tgl_dibuka' => '2025-01-10',
                'tgl_ditutup' => '2025-02-20',
                'tingkat' => 3,
                'jenis' => 1,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Institut Teknologi Bandung',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://kompetisi-itb.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 12.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Lomba Koding Cepat ',
                'tgl_dibuka' => '2025-02-15',
                'tgl_ditutup' => '2025-03-15',
                'tingkat' => 2,
                'jenis' => 1,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Klub Koding Jogja',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://jogjacoding.com/event',
                'biaya' => 25000,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Algorithm Battle ',
                'tgl_dibuka' => '2025-03-01',
                'tgl_ditutup' => '2025-03-20',
                'tingkat' => 2,
                'jenis' => 1,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'PT Logic Solusi',
                'alamat' => 'Online',
                'link_lomba' => 'https://logicsolusi.com/battle',
                'biaya' => 50000,
                'hadiah' => 'Rp 4.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 2: Keamanan Siber
            [
                'nama_lomba' => 'Cyber Defense Competition',
                'tgl_dibuka' => '2025-08-05',
                'tgl_ditutup' => '2025-09-10',
                'tingkat' => 3,
                'jenis' => 2,
                'tingkat_penyelenggara' => 'Organisasi',
                'penyelenggara' => 'ID-CERT',
                'alamat' => 'Jakarta Selatan',
                'link_lomba' => 'https://cyberdefense.id',
                'biaya' => 50000,
                'hadiah' => 'Rp 6.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Capture The Flag UGM (Verifikasi)',
                'tgl_dibuka' => '2025-07-01',
                'tgl_ditutup' => '2025-07-30',
                'tingkat' => 2,
                'jenis' => 2,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Gadjah Mada',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://ctf.ugm.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Hackathon Keamanan (Dibatalkan)',
                'tgl_dibuka' => '2025-09-01',
                'tgl_ditutup' => '2025-09-15',
                'tingkat' => 2,
                'jenis' => 2,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Ethical Hacker Surabaya',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://hacksecure.sby',
                'biaya' => 100000,
                'hadiah' => 'Rp 7.500.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 3: Pengembangan Perangkat Lunak
            [
                'nama_lomba' => 'Challenge Pengembangan Perangkat Lunak',
                'tgl_dibuka' => '2025-03-05',
                'tgl_ditutup' => '2025-04-10',
                'tingkat' => 2,
                'jenis' => 3,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Komunitas Dev Surabaya',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://devsurabaya.org/challenge',
                'biaya' => 25000,
                'hadiah' => 'Rp 7.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Software Dev Challenge (Review)',
                'tgl_dibuka' => '2025-04-01',
                'tgl_ditutup' => '2025-05-01',
                'tingkat' => 2,
                'jenis' => 3,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Universitas Brawijaya',
                'alamat' => 'Malang',
                'link_lomba' => 'https://softwaredev.ub.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 4.500.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Lomba Aplikasi Inovatif (Tidak Memenuhi Syarat)',
                'tgl_dibuka' => '2025-05-10',
                'tgl_ditutup' => '2025-06-10',
                'tingkat' => 2,
                'jenis' => 3,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'PT Cipta Aplikasi',
                'alamat' => 'Online',
                'link_lomba' => 'https://cipta-app.com/lomba',
                'biaya' => 30000,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 4: Sprint Coding
            [
                'nama_lomba' => 'Indonesia Coding Sprint',
                'tgl_dibuka' => '2025-05-03',
                'tgl_ditutup' => '2025-05-18',
                'tingkat' => 2,
                'jenis' => 4,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'PT Digital Nusantara',
                'alamat' => 'Online',
                'link_lomba' => 'https://codingsprint.id',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Speed Coding Bee (Pending)',
                'tgl_dibuka' => '2025-06-01',
                'tgl_ditutup' => '2025-06-05',
                'tingkat' => 2,
                'jenis' => 4,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Bandung Coders',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://bdgcoders.net/sprint',
                'biaya' => 15000,
                'hadiah' => 'Rp 1.500.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Rapid Code Challenge ',
                'tgl_dibuka' => '2025-07-10',
                'tgl_ditutup' => '2025-07-12',
                'tingkat' => 2,
                'jenis' => 4,
                'tingkat_penyelenggara' => 'Organisasi',
                'penyelenggara' => 'Asosiasi Programmer Muda',
                'alamat' => 'Online',
                'link_lomba' => 'https://apm.or.id/rapid',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 5: Sains Data
            [
                'nama_lomba' => 'Kompetisi Data Sains',
                'tgl_dibuka' => '2025-06-15',
                'tgl_ditutup' => '2025-07-15',
                'tingkat' => 3,
                'jenis' => 5,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Universitas Sebelas Maret',
                'alamat' => 'Solo',
                'link_lomba' => 'https://datasains.uns.ac.id',
                'biaya' => 100000,
                'hadiah' => 'Rp 9.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Data Challenge UI (Menunggu Verifikasi)',
                'tgl_dibuka' => '2025-07-20',
                'tgl_ditutup' => '2025-08-20',
                'tingkat' => 3,
                'jenis' => 5,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Universitas Indonesia',
                'alamat' => 'Depok',
                'link_lomba' => 'https://cs.ui.ac.id/datachallenge',
                'biaya' => 75000,
                'hadiah' => 'Rp 8.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Data Mining Cup (Proposal Ditolak)',
                'tgl_dibuka' => '2025-08-01',
                'tgl_ditutup' => '2025-08-30',
                'tingkat' => 2,
                'jenis' => 5,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'DataAnalytica Corp',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://dataanalyticacorp.com/cup',
                'biaya' => 0,
                'hadiah' => 'Rp 6.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 6: Kecerdasan Buatan
            [
                'nama_lomba' => 'AI National Competition',
                'tgl_dibuka' => '2025-07-05',
                'tgl_ditutup' => '2025-08-05',
                'tingkat' => 2,
                'jenis' => 6,
                'tingkat_penyelenggara' => 'Organisasi',
                'penyelenggara' => 'AI Center Indonesia',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://aicenter.id/competition',
                'biaya' => 0,
                'hadiah' => 'Rp 8.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Lomba Kecerdasan Buatan Unair (Menunggu Konfirmasi)',
                'tgl_dibuka' => '2025-08-10',
                'tgl_ditutup' => '2025-09-10',
                'tingkat' => 2,
                'jenis' => 6,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Airlangga',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://ai.unair.ac.id',
                'biaya' => 50000,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'AI for Good ',
                'tgl_dibuka' => '2025-09-15',
                'tgl_ditutup' => '2025-10-15',
                'tingkat' => 2,
                'jenis' => 6,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Social AI Community',
                'alamat' => 'Online',
                'link_lomba' => 'https://socialai.org/challenge',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 7: Desain Antarmuka
            [
                'nama_lomba' => 'Kompetisi Desain Antarmuka',
                'tgl_dibuka' => '2025-09-05',
                'tgl_ditutup' => '2025-09-25',
                'tingkat' => 2,
                'jenis' => 7,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Universitas Ciputra',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://desain.ciputra.ac.id',
                'biaya' => 30000,
                'hadiah' => 'Rp 4.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'UI/UX Challenge Binus (Review Proposal)',
                'tgl_dibuka' => '2025-10-01',
                'tgl_ditutup' => '2025-10-30',
                'tingkat' => 2,
                'jenis' => 7,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Bina Nusantara',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://uiux.binus.ac.id',
                'biaya' => 40000,
                'hadiah' => 'Rp 3.500.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Web Design Contest ',
                'tgl_dibuka' => '2025-11-05',
                'tgl_ditutup' => '2025-11-25',
                'tingkat' => 1,
                'jenis' => 7,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Desainer Grafis Malang',
                'alamat' => 'Malang',
                'link_lomba' => 'https://dgm.com/contest',
                'biaya' => 0,
                'hadiah' => 'Rp 1.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 8: Pengembangan Game
            [
                'nama_lomba' => 'Game Creation Contest',
                'tgl_dibuka' => '2025-10-05',
                'tgl_ditutup' => '2025-11-05',
                'tingkat' => 2,
                'jenis' => 8,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'GameDev Indonesia',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://gamedev.id/contest',
                'biaya' => 0,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Indie Game Jam (Review)',
                'tgl_dibuka' => '2025-11-10',
                'tgl_ditutup' => '2025-11-13',
                'tingkat' => 2,
                'jenis' => 8,
                'tingkat_penyelenggara' => 'Organisasi',
                'penyelenggara' => 'Asosiasi Game Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://agi.or.id/gamejam',
                'biaya' => 50000,
                'hadiah' => 'Rp 6.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Lomba Game Edukasi ',
                'tgl_dibuka' => '2025-12-01',
                'tgl_ditutup' => '2025-12-20',
                'tingkat' => 2,
                'jenis' => 8,
                'tingkat_penyelenggara' => 'Pemerintah',
                'penyelenggara' => 'Kemendikbud Ristek',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://edugame.kemdikbud.go.id',
                'biaya' => 0,
                'hadiah' => 'Rp 10.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 9: Jaringan Komputer
            [
                'nama_lomba' => 'Network Engineering Competition',
                'tgl_dibuka' => '2025-11-05',
                'tgl_ditutup' => '2025-12-05',
                'tingkat' => 2,
                'jenis' => 9,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'PT Netindo',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://netindo.id/competition',
                'biaya' => 40000,
                'hadiah' => 'Rp 2.500.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Cisco NetRiders (Pending)',
                'tgl_dibuka' => '2025-10-01',
                'tgl_ditutup' => '2025-10-30',
                'tingkat' => 3,
                'jenis' => 9,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'Cisco Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://netacad.com/netriders',
                'biaya' => 0,
                'hadiah' => 'Rp 15.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Mikrotik Challenge ',
                'tgl_dibuka' => '2025-09-01',
                'tgl_ditutup' => '2025-09-20',
                'tingkat' => 2,
                'jenis' => 9,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Komunitas Mikrotik Malang',
                'alamat' => 'Malang',
                'link_lomba' => 'https://mikrotik-mlg.com/chal',
                'biaya' => 50000,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 10: Robotika
            [
                'nama_lomba' => 'Kompetisi Robotika Nasional',
                'tgl_dibuka' => '2025-06-05',
                'tgl_ditutup' => '2025-07-05',
                'tingkat' => 3,
                'jenis' => 10,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Universitas Negeri Makassar',
                'alamat' => 'Makassar',
                'link_lomba' => 'https://robotika.unm.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Kontes Robot Terbang Indonesia (Review)',
                'tgl_dibuka' => '2025-07-10',
                'tgl_ditutup' => '2025-08-10',
                'tingkat' => 3,
                'jenis' => 10,
                'tingkat_penyelenggara' => 'Pemerintah',
                'penyelenggara' => 'Puspresnas',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://puspresnas.kemdikbud.go.id/krti',
                'biaya' => 250000,
                'hadiah' => 'Rp 20.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Battle Bot Mini ',
                'tgl_dibuka' => '2025-08-15',
                'tgl_ditutup' => '2025-09-15',
                'tingkat' => 2,
                'jenis' => 10,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'RoboClub Surabaya',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://roboclub.sby/battle',
                'biaya' => 100000,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 11: Internet of Things (IoT)
            [
                'nama_lomba' => 'IoT National Challenge',
                'tgl_dibuka' => '2025-03-20',
                'tgl_ditutup' => '2025-04-20',
                'tingkat' => 2,
                'jenis' => 11,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'IoT Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://iotindonesia.id/challenge',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'IoT Innovation UB (Pending)',
                'tgl_dibuka' => '2025-04-25',
                'tgl_ditutup' => '2025-05-25',
                'tingkat' => 2,
                'jenis' => 11,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Universitas Brawijaya',
                'alamat' => 'Malang',
                'link_lomba' => 'https://iot.ub.ac.id',
                'biaya' => 50000,
                'hadiah' => 'Rp 4.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Smart Home Project ',
                'tgl_dibuka' => '2025-05-30',
                'tgl_ditutup' => '2025-06-30',
                'tingkat' => 2,
                'jenis' => 11,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'PT Rumah Pintar',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://rumahpintar.com/project',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 12: Business Case
            [
                'nama_lomba' => 'Business Case Competition',
                'tgl_dibuka' => '2025-04-01',
                'tgl_ditutup' => '2025-05-01',
                'tingkat' => 2,
                'jenis' => 12,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Airlangga',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://businesscase.unair.ac.id',
                'biaya' => 15000,
                'hadiah' => 'Rp 3.500.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Startup Case Challenge (Review)',
                'tgl_dibuka' => '2025-05-05',
                'tgl_ditutup' => '2025-06-05',
                'tingkat' => 2,
                'jenis' => 12,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'Ventura Capital Inc.',
                'alamat' => 'Online',
                'link_lomba' => 'https://venturacap.com/case',
                'biaya' => 100000,
                'hadiah' => 'Rp 10.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Marketing Plan Competition ',
                'tgl_dibuka' => '2025-06-10',
                'tgl_ditutup' => '2025-07-10',
                'tingkat' => 2,
                'jenis' => 12,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Prasetiya Mulya',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://marketing.prasmul.ac.id',
                'biaya' => 75000,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 13: Mobile Development
            [
                'nama_lomba' => 'Mobile Development Competition',
                'tgl_dibuka' => '2025-05-10',
                'tgl_ditutup' => '2025-06-10',
                'tingkat' => 2,
                'jenis' => 13,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Padjadjaran',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://mobiledev.unpad.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 4.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Android Developer Challenge (Pending)',
                'tgl_dibuka' => '2025-06-15',
                'tgl_ditutup' => '2025-07-15',
                'tingkat' => 2,
                'jenis' => 13,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Google Developer Group Jakarta',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://gdgjakarta.org/android',
                'biaya' => 0,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'iOS App Contest ',
                'tgl_dibuka' => '2025-07-20',
                'tgl_ditutup' => '2025-08-20',
                'tingkat' => 2,
                'jenis' => 13,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'iSolution Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://isolution.id/contest',
                'biaya' => 50000,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 14: Web Development
            [
                'nama_lomba' => 'Web Development Challenge',
                'tgl_dibuka' => '2025-07-15',
                'tgl_ditutup' => '2025-08-15',
                'tingkat' => 2,
                'jenis' => 14,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Negeri Jakarta',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://webdev.unj.ac.id',
                'biaya' => 25000,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Full-Stack Competition (Pending)',
                'tgl_dibuka' => '2025-08-20',
                'tgl_ditutup' => '2025-09-20',
                'tingkat' => 2,
                'jenis' => 14,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'PT Kodingan Sejahtera',
                'alamat' => 'Online',
                'link_lomba' => 'https://kodingan.com/fullstack',
                'biaya' => 0,
                'hadiah' => 'Rp 7.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Front-End Battle ',
                'tgl_dibuka' => '2025-09-25',
                'tgl_ditutup' => '2025-10-25',
                'tingkat' => 2,
                'jenis' => 14,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'CSS Club Indonesia',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://cssclub.id/battle',
                'biaya' => 30000,
                'hadiah' => 'Rp 2.500.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 15: Animasi Digital
            [
                'nama_lomba' => 'Digital Animation Contest',
                'tgl_dibuka' => '2025-08-10',
                'tgl_ditutup' => '2025-09-10',
                'tingkat' => 2,
                'jenis' => 15,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Institut Seni Indonesia',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://animation.isi.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Lomba Film Animasi Pendek (Review)',
                'tgl_dibuka' => '2025-09-15',
                'tgl_ditutup' => '2025-10-15',
                'tingkat' => 2,
                'jenis' => 15,
                'tingkat_penyelenggara' => 'Pemerintah',
                'penyelenggara' => 'Bekraf',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://bekraf.go.id/animasi',
                'biaya' => 0,
                'hadiah' => 'Rp 15.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => '3D Character Modeling ',
                'tgl_dibuka' => '2025-10-20',
                'tgl_ditutup' => '2025-11-20',
                'tingkat' => 2,
                'jenis' => 15,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => '3D Artist Community',
                'alamat' => 'Online',
                'link_lomba' => 'https://3dartist.id/lomba',
                'biaya' => 50000,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 16: Cloud Computing
            [
                'nama_lomba' => 'Cloud Computing Competition',
                'tgl_dibuka' => '2025-09-15',
                'tgl_ditutup' => '2025-10-15',
                'tingkat' => 2,
                'jenis' => 16,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Kristen Petra',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://cloudcomp.ukp.ac.id',
                'biaya' => 50000,
                'hadiah' => 'Rp 2.500.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'AWS Cloud Challenge (Pending)',
                'tgl_dibuka' => '2025-10-20',
                'tgl_ditutup' => '2025-11-20',
                'tingkat' => 3,
                'jenis' => 16,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'Amazon Web Services Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://aws.amazon.com/id/challenge',
                'biaya' => 0,
                'hadiah' => 'Rp 20.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Azure DevOps Contest ',
                'tgl_dibuka' => '2025-11-25',
                'tgl_ditutup' => '2025-12-25',
                'tingkat' => 2,
                'jenis' => 16,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'PT Cloud Nusantara',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://cloudnusantara.id/contest',
                'biaya' => 75000,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 17: Forensik Digital
            [
                'nama_lomba' => 'Digital Forensics Challenge',
                'tgl_dibuka' => '2025-10-20',
                'tgl_ditutup' => '2025-11-20',
                'tingkat' => 2,
                'jenis' => 17,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Trunojoyo Madura',
                'alamat' => 'Bangkalan',
                'link_lomba' => 'https://forensics.trunojoyo.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Incident Response Competition (Pending)',
                'tgl_dibuka' => '2025-11-01',
                'tgl_ditutup' => '2025-11-30',
                'tingkat' => 2,
                'jenis' => 17,
                'tingkat_penyelenggara' => 'Organisasi',
                'penyelenggara' => 'Asosiasi Forensik Digital Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://afdi.or.id/ir-comp',
                'biaya' => 100000,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Malware Analysis Contest ',
                'tgl_dibuka' => '2025-09-01',
                'tgl_ditutup' => '2025-09-30',
                'tingkat' => 2,
                'jenis' => 17,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'CyberSecure Labs',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://cybersecure.id/contest',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 18: Kriptografi
            [
                'nama_lomba' => 'Cryptography Challenge',
                'tgl_dibuka' => '2025-11-25',
                'tgl_ditutup' => '2025-12-25',
                'tingkat' => 2,
                'jenis' => 18,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Sanata Dharma',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://crypto.usd.ac.id',
                'biaya' => 10000,
                'hadiah' => 'Rp 1.500.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Enkripsi-Dekripsi Lomba (Pending)',
                'tgl_dibuka' => '2025-10-10',
                'tgl_ditutup' => '2025-11-10',
                'tingkat' => 2,
                'jenis' => 18,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Komunitas Kriptografi Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://kripto.id/lomba',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Steganography Contest ',
                'tgl_dibuka' => '2025-09-05',
                'tgl_ditutup' => '2025-10-05',
                'tingkat' => 2,
                'jenis' => 18,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Institut Teknologi Telkom',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://ittelkom.ac.id/stego',
                'biaya' => 25000,
                'hadiah' => 'Rp 1.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 19: Desain UI/UX
            [
                'nama_lomba' => 'Lomba Desain UI/UX',
                'tgl_dibuka' => '2025-02-01',
                'tgl_ditutup' => '2025-03-01',
                'tingkat' => 2,
                'jenis' => 19,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Politeknik Negeri Malang',
                'alamat' => 'Malang',
                'link_lomba' => 'https://uiux-poltek.com',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'UX Research Competition (Pending)',
                'tgl_dibuka' => '2025-03-10',
                'tgl_ditutup' => '2025-04-10',
                'tingkat' => 2,
                'jenis' => 19,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'UX Indonesia',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://uxindo.com/competition',
                'biaya' => 50000,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Mobile UI Redesign ',
                'tgl_dibuka' => '2025-04-15',
                'tgl_ditutup' => '2025-05-15',
                'tingkat' => 2,
                'jenis' => 19,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Desainer Produk Jogja',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://dpj.id/redesign',
                'biaya' => 20000,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 20: Hackathon
            [
                'nama_lomba' => 'Hackathon Inovasi Digital',
                'tgl_dibuka' => '2025-04-10',
                'tgl_ditutup' => '2025-04-12',
                'tingkat' => 2,
                'jenis' => 20,
                'tingkat_penyelenggara' => 'Pemerintah',
                'penyelenggara' => 'Dinas Kominfo Jawa Timur',
                'alamat' => 'Surabaya',
                'link_lomba' => 'https://hackathon-jatim.go.id',
                'biaya' => 75000,
                'hadiah' => 'Rp 7.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Fintech Hackathon (Pending)',
                'tgl_dibuka' => '2025-05-20',
                'tgl_ditutup' => '2025-05-22',
                'tingkat' => 3,
                'jenis' => 20,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'Bank Digital Asia',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://bda.com/hackathon',
                'biaya' => 0,
                'hadiah' => 'Rp 25.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Healthtech Hack ',
                'tgl_dibuka' => '2025-06-05',
                'tgl_ditutup' => '2025-06-07',
                'tingkat' => 2,
                'jenis' => 20,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Inovator Kesehatan',
                'alamat' => 'Online',
                'link_lomba' => 'https://healthtech.id/hack',
                'biaya' => 50000,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 21: Startup Pitching
            [
                'nama_lomba' => 'Startup Pitch Competition',
                'tgl_dibuka' => '2025-01-15',
                'tgl_ditutup' => '2025-02-15',
                'tingkat' => 2,
                'jenis' => 21,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Prasetiya Mulya',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://startup.prasmul.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Business Idea Pitching (Pending)',
                'tgl_dibuka' => '2025-02-20',
                'tgl_ditutup' => '2025-03-20',
                'tingkat' => 2,
                'jenis' => 21,
                'tingkat_penyelenggara' => 'Universitas',
                'penyelenggara' => 'Universitas Indonesia',
                'alamat' => 'Depok',
                'link_lomba' => 'https://pitching.ui.ac.id',
                'biaya' => 100000,
                'hadiah' => 'Rp 7.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Social Enterprise Pitch ',
                'tgl_dibuka' => '2025-03-25',
                'tgl_ditutup' => '2025-04-25',
                'tingkat' => 2,
                'jenis' => 21,
                'tingkat_penyelenggara' => 'Organisasi',
                'penyelenggara' => 'Yayasan Inovasi Sosial',
                'alamat' => 'Online',
                'link_lomba' => 'https://yis.org/pitch',
                'biaya' => 0,
                'hadiah' => 'Rp 4.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 22: Desain Algoritma
            [
                'nama_lomba' => 'Algorithm Design Competition',
                'tgl_dibuka' => '2025-03-20',
                'tgl_ditutup' => '2025-04-20',
                'tingkat' => 2,
                'jenis' => 22,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Atma Jaya',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://algodesign.uajy.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Competitive Programming Unpad (Pending)',
                'tgl_dibuka' => '2025-04-25',
                'tgl_ditutup' => '2025-05-25',
                'tingkat' => 2,
                'jenis' => 22,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Padjadjaran',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://cp.unpad.ac.id',
                'biaya' => 30000,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Data Structure Challenge ',
                'tgl_dibuka' => '2025-05-30',
                'tgl_ditutup' => '2025-06-30',
                'tingkat' => 2,
                'jenis' => 22,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Klub Algoritma Nasional',
                'alamat' => 'Online',
                'link_lomba' => 'https://kan.id/ds-challenge',
                'biaya' => 0,
                'hadiah' => 'Rp 1.500.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 23: Machine Learning
            [
                'nama_lomba' => 'Machine Learning Competition',
                'tgl_dibuka' => '2025-05-20',
                'tgl_ditutup' => '2025-06-20',
                'tingkat' => 2,
                'jenis' => 23,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Hasanuddin',
                'alamat' => 'Makassar',
                'link_lomba' => 'https://ml.hasanuddin.ac.id',
                'biaya' => 30000,
                'hadiah' => 'Rp 4.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Deep Learning Challenge (Pending)',
                'tgl_dibuka' => '2025-06-25',
                'tgl_ditutup' => '2025-07-25',
                'tingkat' => 3,
                'jenis' => 23,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'AI Corp',
                'alamat' => 'Online',
                'link_lomba' => 'https://aicorp.com/dl-challenge',
                'biaya' => 100000,
                'hadiah' => 'Rp 10.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Predictive Modeling Contest ',
                'tgl_dibuka' => '2025-07-30',
                'tgl_ditutup' => '2025-08-30',
                'tingkat' => 2,
                'jenis' => 23,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Data Science Jakarta',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://dsjkt.org/predict',
                'biaya' => 0,
                'hadiah' => 'Rp 3.500.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 24: Augmented Reality
            [
                'nama_lomba' => 'Augmented Reality Competition',
                'tgl_dibuka' => '2025-07-20',
                'tgl_ditutup' => '2025-08-20',
                'tingkat' => 2,
                'jenis' => 24,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Negeri Semarang',
                'alamat' => 'Semarang',
                'link_lomba' => 'https://ar.unnes.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'AR Filter Contest (Pending)',
                'tgl_dibuka' => '2025-08-25',
                'tgl_ditutup' => '2025-09-25',
                'tingkat' => 2,
                'jenis' => 24,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'Meta Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://meta.com/id/ar-contest',
                'biaya' => 0,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'AR for Education ',
                'tgl_dibuka' => '2025-09-30',
                'tgl_ditutup' => '2025-10-30',
                'tingkat' => 2,
                'jenis' => 24,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Pendidikan Indonesia',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://ar.upi.edu',
                'biaya' => 25000,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 25: Virtual Reality
            [
                'nama_lomba' => 'Virtual Reality Competition',
                'tgl_dibuka' => '2025-09-20',
                'tgl_ditutup' => '2025-10-20',
                'tingkat' => 2,
                'jenis' => 25,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Negeri Yogyakarta',
                'alamat' => 'Yogyakarta',
                'link_lomba' => 'https://vr.uny.ac.id',
                'biaya' => 20000,
                'hadiah' => 'Rp 2.500.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'VR Game Development (Pending)',
                'tgl_dibuka' => '2025-10-25',
                'tgl_ditutup' => '2025-11-25',
                'tingkat' => 2,
                'jenis' => 25,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'VR Devs Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://vrdevs.id/gamedev',
                'biaya' => 50000,
                'hadiah' => 'Rp 4.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Immersive Experience Design ',
                'tgl_dibuka' => '2025-11-30',
                'tgl_ditutup' => '2025-12-30',
                'tingkat' => 2,
                'jenis' => 25,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'Immersive Tech',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://immersivetech.com/design',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 26: Blockchain
            [
                'nama_lomba' => 'Blockchain Challenge Indonesia',
                'tgl_dibuka' => '2025-11-20',
                'tgl_ditutup' => '2025-12-20',
                'tingkat' => 2,
                'jenis' => 26,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Gunadarma',
                'alamat' => 'Depok',
                'link_lomba' => 'https://blockchain.gunadarma.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 3.500.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Decentralized App (dApp) Contest (Pending)',
                'tgl_dibuka' => '2025-10-15',
                'tgl_ditutup' => '2025-11-15',
                'tingkat' => 2,
                'jenis' => 26,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Asosiasi Blockchain Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://abi.or.id/dapp-contest',
                'biaya' => 100000,
                'hadiah' => 'Rp 8.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Smart Contract Development ',
                'tgl_dibuka' => '2025-09-10',
                'tgl_ditutup' => '2025-10-10',
                'tingkat' => 2,
                'jenis' => 26,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'Crypto Exchange ID',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://cryptoexchange.id/dev',
                'biaya' => 0,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 27: Inovasi Aplikasi
            [
                'nama_lomba' => 'App Innovation Competition',
                'tgl_dibuka' => '2025-01-05',
                'tgl_ditutup' => '2025-02-05',
                'tingkat' => 2,
                'jenis' => 27,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Katolik Parahyangan',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://appinnovation.unpar.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Student App Challenge (Pending)',
                'tgl_dibuka' => '2025-02-10',
                'tgl_ditutup' => '2025-03-10',
                'tingkat' => 2,
                'jenis' => 27,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'Samsung Indonesia',
                'alamat' => 'Online',
                'link_lomba' => 'https://samsung.com/id/app-chal',
                'biaya' => 0,
                'hadiah' => 'Rp 10.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Cross-Platform App Contest ',
                'tgl_dibuka' => '2025-03-15',
                'tgl_ditutup' => '2025-04-15',
                'tingkat' => 2,
                'jenis' => 27,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Flutter Devs Malang',
                'alamat' => 'Malang',
                'link_lomba' => 'https://fluttermlg.id/contest',
                'biaya' => 30000,
                'hadiah' => 'Rp 2.500.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 28: Desain Database
            [
                'nama_lomba' => 'Database Design Competition',
                'tgl_dibuka' => '2025-03-05',
                'tgl_ditutup' => '2025-04-05',
                'tingkat' => 2,
                'jenis' => 28,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Kristen Satya Wacana',
                'alamat' => 'Salatiga',
                'link_lomba' => 'https://dbdesign.uksw.edu',
                'biaya' => 10000,
                'hadiah' => 'Rp 2.500.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'SQL Query Contest (Pending)',
                'tgl_dibuka' => '2025-04-10',
                'tgl_ditutup' => '2025-05-10',
                'tingkat' => 2,
                'jenis' => 28,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'SQL Enthusiast ID',
                'alamat' => 'Online',
                'link_lomba' => 'https://sql-id.org/contest',
                'biaya' => 0,
                'hadiah' => 'Rp 1.500.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'NoSQL Challenge ',
                'tgl_dibuka' => '2025-05-15',
                'tgl_ditutup' => '2025-06-15',
                'tingkat' => 2,
                'jenis' => 28,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'Big Data Solutions',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://bigdata.com/nosql',
                'biaya' => 40000,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 29: Digital Marketing
            [
                'nama_lomba' => 'Digital Marketing Competition',
                'tgl_dibuka' => '2025-05-05',
                'tgl_ditutup' => '2025-06-05',
                'tingkat' => 2,
                'jenis' => 29,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Mercu Buana',
                'alamat' => 'Jakarta',
                'link_lomba' => 'https://digitalmarketing.mercubuana.ac.id',
                'biaya' => 0,
                'hadiah' => 'Rp 2.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'SEO Challenge (Pending)',
                'tgl_dibuka' => '2025-06-10',
                'tgl_ditutup' => '2025-07-10',
                'tingkat' => 2,
                'jenis' => 29,
                'tingkat_penyelenggara' => 'Perusahaan',
                'penyelenggara' => 'Agensi Digital Marka',
                'alamat' => 'Online',
                'link_lomba' => 'https://marka.agency/seo-chal',
                'biaya' => 50000,
                'hadiah' => 'Rp 4.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Social Media Campaign Contest ',
                'tgl_dibuka' => '2025-07-15',
                'tgl_ditutup' => '2025-08-15',
                'tingkat' => 2,
                'jenis' => 29,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'Social Media Specialist ID',
                'alamat' => 'Bandung',
                'link_lomba' => 'https://sms-id.org/contest',
                'biaya' => 0,
                'hadiah' => 'Rp 3.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jenis 30: E-Sports
            [
                'nama_lomba' => 'E-Sports Tournament',
                'tgl_dibuka' => '2025-07-05',
                'tgl_ditutup' => '2025-08-05',
                'tingkat' => 2,
                'jenis' => 30,
                'tingkat_penyelenggara' => 'Kampus Lain',
                'penyelenggara' => 'Universitas Negeri Malang',
                'alamat' => 'Malang',
                'link_lomba' => 'https://esports.um.ac.id',
                'biaya' => 50000,
                'hadiah' => 'Rp 5.000.000',
                'verifikasi' => 'Accepted',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Campus Gaming League (Verifikasi Sponsor)',
                'tgl_dibuka' => '2025-08-10',
                'tgl_ditutup' => '2025-09-10',
                'tingkat' => 2,
                'jenis' => 30,
                'tingkat_penyelenggara' => 'Organisasi',
                'penyelenggara' => 'Asosiasi E-Sports Mahasiswa',
                'alamat' => 'Online',
                'link_lomba' => 'https://aem.id/league',
                'biaya' => 100000,
                'hadiah' => 'Rp 10.000.000',
                'verifikasi' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lomba' => 'Turnamen Valorant Antar Fakultas ',
                'tgl_dibuka' => '2025-09-15',
                'tgl_ditutup' => '2025-09-30',
                'tingkat' => 1,
                'jenis' => 30,
                'tingkat_penyelenggara' => 'Komunitas',
                'penyelenggara' => 'UKM E-Sports Polinema',
                'alamat' => 'Malang',
                'link_lomba' => 'https://esports.polinema.ac.id/valo',
                'biaya' => 25000,
                'hadiah' => 'Rp 1.000.000',
                'verifikasi' => 'Rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
